### ISSUE TITLE
can't run on non-English Windows

### ISSUE THREAD

**Issue by garfieldnate** [jamesshore/automatopia#1]
The npm modules that use http-server need to be updated in order to run on non-English Windows. See https://github.com/indexzero/http-server/issues/244 for details on the issue. http-server should be at least 0.9.0 and karma should be at least 0.13.20. I also updated Browserify, but I don't think that was necessary.

**Comment by jamesshore** [comment]
Nice catch, thank you. My schedule's very full at the moment but I'll get to this as soon as I can.

**Comment by jamesshore** [comment]
Updated all dependencies, please check and confirm that it fixed the issue, thanks!

**Comment by garfieldnate** [comment]
Works great, thanks!
