### ISSUE TITLE
Why not automate karma browser launch?

### ISSUE THREAD

**Issue by halcwb** [jamesshore/automatopia#3]
I watched the early episodes. At some point the launching and capturing of browsers by karma was automated. However, in the current version you have to setup everything manually to perform the tests. This doesn't fit well with a setup using continuous integration with for example Travis.

Why is it that you have to do everything manually to run the bowser tests?

**Comment by jamesshore** [comment]
Three reasons:

1) Some browsers (IE in a VM on Mac, iOS, Android) aren't easily automated. 
2) Also, browsers occasionally disconnect randomly and have to be restarted. 
3) Karma will automatically start and capture (some) browsers for you, but it automatically shuts them down after each test run, which adds many seconds to test run. Too slow given that my target build time is <5 sec.

Overall, the cost/benefit of automated browser start isn't there. It's easier to just start them once at the beginning of your work day.

However, if you want to automatically start the browser for e.g., TravisCI, you can replace `build/util/karma_runner.js` with the npm module `simplebuild-karma` (which is the same thing, npm-ified) and use the 'capture' option.

(Eventually I intend to update automatopia to use simplebuild-karma, just haven't gotten to it yet.)

**Comment by garfieldnate** [comment]
Works great, thanks!
